<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="EmployeeInformationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ICPL11510;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EmployeeDetail" Member="EmployeeDetails">
    <Type Name="EmployeeDetail">
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactInfo" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
    </Type>
  </Table>
</Database>